name: vimdoc

on:
  push:
    paths: &docs_paths
      - "README.md"
      - "doc/nix-update.txt"
      - ".github/workflows/autogen.yml"
  pull_request:
    paths: *docs_paths
  workflow_dispatch:

permissions:
  contents: read

jobs:
  vimdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: panvimdoc
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: nix-update
          version: "NVIM v0.13.0"
          description: "Dynamically and asynchronously update fetch-like Nix attributes"
      - name: check generated vimdoc
        run: git diff --exit-code -- doc/nix-update.txt
